INSERT INTO  sucursales (cod_sucursal,nombre) values ('DH','SEDE CHORRILLOS');
INSERT INTO  sucursales (cod_sucursal,nombre) values ('A5','SEDE VILLA SALVADOR');

INSERT PRODUCTOS VALUES ('P1','PRODUCTO 1',100);
INSERT PRODUCTOS VALUES ('P2','PRODUCTO 2',200);
INSERT PRODUCTOS VALUES ('P3','PRODUCTO 3',300);

INSERT USUARIOS  (COD_USUARIO,NOMBRE,USER,PASSWORD,COD_SUCURSAL)  VALUES ('U1','VICTOR','MSVICTOR','PERU12$$','DH')
INSERT USUARIOS (COD_USUARIO,NOMBRE,USER,PASSWORD,COD_SUCURSAL) VALUES ('U2','KEVIN','MSKEVIN','PERU12$$','A5')
